# Generated by Django 3.2.6 on 2025-02-14 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_license_plate', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('color', models.CharField(choices=[('white', 'سفید'), ('black', 'سیاه'), ('silver', 'نقره\u200cای'), ('gray', 'طوسی')], default='black', max_length=10)),
                ('car_type', models.CharField(choices=[('baari', 'باری'), ('sedan', 'سدان')], default='baari', max_length=10)),
                ('usage', models.PositiveIntegerField(blank=True, null=True)),
                ('company', models.CharField(choices=[('Toyota', 'تویوتا'), ('Neisan', 'سدان'), ('Benz', 'بنز')], default='Toyota', max_length=10)),
                ('ownership', models.CharField(choices=[('private', 'شخصی'), ('public', 'شرکتی')], default='public', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('production_date', models.DateField(default=django.utils.timezone.now)),
                ('fuel', models.CharField(choices=[('Petrol', 'بنزین'), ('Diesel', 'گازویل'), ('Gas', 'گاز')], default='petrol', max_length=10)),
                ('load_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=20, null=True)),
                ('motor_number', models.CharField(blank=True, max_length=20, null=True)),
                ('VIN_number', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_number', models.CharField(max_length=20, unique=True)),
                ('insurance_company', models.CharField(choices=[('Asia', 'بیمه آسیا'), ('Iran', 'بیمه ایران')], default='Asia', max_length=10)),
                ('car_insurance_start_date', models.DateField(default=django.utils.timezone.now)),
                ('car_insurance_end_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('available', 'دردسترس'), ('not available', 'در حال ماموریت'), ('fixing', 'در حال تعمیر')], default='available', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sertificate', models.CharField(choices=[('p1', 'پایه 1'), ('p2', 'پایه 2'), ('p3', 'پایه 3')], default='p3', max_length=10)),
                ('sertificate_expiration_date', models.DateField(default=django.utils.timezone.now)),
                ('experience', models.PositiveIntegerField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=10)),
                ('insurance', models.CharField(choices=[('have', 'دارد'), ('dont have', 'ندارد')], default='have', max_length=10)),
                ('insurance_num', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('birthday_date', models.DateField(default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('home_address', models.TextField()),
                ('identification_code', models.CharField(max_length=10)),
                ('driver_phone_number', models.CharField(max_length=11)),
                ('driver_phone_number2', models.CharField(blank=True, max_length=11, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='driver_profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('is_available', models.CharField(choices=[('available', 'آماده به کار'), ('not available', 'تایم مرخصی'), ('abscense', 'غایب')], default='available', max_length=20)),
                ('cars', models.ManyToManyField(blank=True, related_name='cars', to='transportation.Car')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drives', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_subject', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[('open', 'در حال انجام'), ('closed', 'انجام شده')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='transportation.car')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='transportation.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_check_by_user', models.BooleanField(default=False)),
                ('oil_check_each_total_distance', models.PositiveIntegerField()),
                ('oil_check_alarm', models.BooleanField(default=False)),
                ('filter_check_by_user', models.BooleanField(default=False)),
                ('filter_check_each_total_distance', models.PositiveIntegerField()),
                ('filter_check_alarm', models.BooleanField(default=False)),
                ('motor_check_by_user', models.BooleanField(default=False)),
                ('motor_check_each_total_distance', models.PositiveIntegerField()),
                ('motor_check_alarm', models.BooleanField(default=False)),
                ('tire_check_by_user', models.BooleanField(default=False)),
                ('tire_check_each_total_distance', models.PositiveIntegerField()),
                ('tire_check_alarm', models.BooleanField(default=False)),
                ('fuel_check_by_user', models.BooleanField(default=False)),
                ('fuel_check_each_total_distance', models.PositiveIntegerField()),
                ('fuel_check_alarm', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_maintenance', to='transportation.car')),
            ],
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['created_at', 'created_by'], name='created_atby_index_driver'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['created_at', 'created_by'], name='created_atby_index_car'),
        ),
    ]
