# Generated by Django 5.1.6 on 2025-02-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.CharField(choices=[('Toyota', 'تویوتا'), ('Neisan', 'نیسان'), ('Benz', 'بنز')], default='Toyota', max_length=10),
        ),
    ]
