# Generated by Django 5.1.6 on 2025-02-23 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_alter_car_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_insurance_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_insurance_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_maintenance', to='transportation.car'),
        ),
    ]
