# Generated by Django 5.1.6 on 2025-02-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_alter_car_car_insurance_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmaintenance',
            name='filter_check_each_total_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='fuel_check_each_total_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='motor_check_each_total_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='oil_check_each_total_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='tire_check_each_total_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
