# Generated by Django 5.1.6 on 2025-02-23 10:06

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0004_alter_carmaintenance_filter_check_each_total_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_insurance_end_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_insurance_start_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='production_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
    ]
