# Generated by Django 5.1.6 on 2025-02-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0007_alter_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(default=0),
        ),
    ]
