# Generated by Django 5.1.6 on 2025-02-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0008_task_distance_alter_task_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='usage',
        ),
        migrations.AddField(
            model_name='car',
            name='initial_usage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='temporary_usage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
