# Generated by Django 5.1.6 on 2025-02-25 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0009_remove_car_usage_car_initial_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_insurance_end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_insurance_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='car',
            name='production_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
