# Generated by Django 5.1.6 on 2025-02-26 14:12

import apps.transportation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0010_alter_car_car_insurance_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('notification_model_type', models.CharField(choices=[('car', 'Car Notification'), ('task', 'Task Notification'), ('driver', 'Driver Notification')], max_length=10)),
                ('notification_importance', models.CharField(choices=[('عادی', 'normal'), ('متوسط', 'average'), ('فوری', 'urgant')], max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='carmaintenance',
            name='default_maintenance_info',
            field=models.JSONField(default=apps.transportation.models.default_maintenance_info),
        ),
    ]
