# Generated by Django 5.1.6 on 2025-02-27 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0011_notification_carmaintenance_default_maintenance_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birthday_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='driver',
            name='sertificate_expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_importance',
            field=models.CharField(choices=[('normal', 'عادی'), ('average', 'متوسط'), ('فورurgantی', 'فوری')], max_length=10),
        ),
    ]
