# Generated by Django 5.1.6 on 2025-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0012_alter_driver_birthday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'در حال انجام'), ('closed', 'انجام شده'), ('lated', 'دیرکرد')], default='open', max_length=10),
        ),
    ]
