# Generated by Django 5.1.6 on 2025-02-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0013_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='is_available',
            field=models.CharField(choices=[('available', 'آماده به کار'), ('not available', 'تایم مرخصی'), ('at work', 'در ماموریت')], default='available', max_length=20),
        ),
    ]
