# Generated by Django 5.1.6 on 2025-02-28 10:07

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0014_alter_driver_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
