# Generated by Django 5.1.6 on 2025-02-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0015_alter_task_created_at_alter_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'دردسترس'), ('at work', 'در حال ماموریت'), ('fixing', 'در حال تعمیر')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='car',
            field=models.ForeignKey(limit_choices_to={'status': 'available'}, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='transportation.car'),
        ),
        migrations.AlterField(
            model_name='task',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'status': 'available'}, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='transportation.driver'),
        ),
    ]
