# Generated by Django 5.1.6 on 2025-03-02 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0016_alter_car_status_alter_task_car_alter_task_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_importance',
            field=models.CharField(choices=[('normal', 'عادی'), ('average', 'متوسط'), ('urgant', 'فوری')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'is_available': 'available'}, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='transportation.driver'),
        ),
    ]
