# Generated by Django 5.1.6 on 2025-03-02 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0017_alter_notification_notification_importance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SelectedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('point1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='transportation.predefinedpoint')),
                ('point2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='transportation.predefinedpoint')),
            ],
        ),
    ]
