# Generated by Django 5.1.6 on 2025-03-02 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0018_predefinedpoint_selectedroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_routes', to='transportation.predefinedpoint')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_routes', to='transportation.predefinedpoint')),
            ],
        ),
        migrations.DeleteModel(
            name='SelectedRoute',
        ),
    ]
