# Generated by Django 5.1.6 on 2025-03-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0019_route_delete_selectedroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_importance',
            field=models.CharField(choices=[('normal', 'عادی'), ('warning', 'متوسط'), ('urgant', 'فوری')], max_length=10),
        ),
    ]
