# Generated by Django 5.1.6 on 2025-03-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0021_alter_task_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='transportation.task'),
        ),
    ]
