# Generated by Django 5.1.6 on 2025-03-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0022_route_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='task',
        ),
    ]
