# Generated by Django 5.1.6 on 2025-03-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0023_remove_route_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_model_type',
            field=models.CharField(choices=[('car', 'اعلان خودرها'), ('task', 'اعلام ماموریت\u200cها'), ('driver', 'اعلان رانندگان')], max_length=10),
        ),
    ]
