# Generated by Django 5.1.6 on 2025-03-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0024_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_mount',
            field=models.IntegerField(default=40),
        ),
    ]
